version: '3'

services:

  phpipam:
  
    image: phpipam/phpipam-www:latest
    container_name: phpipam
    hostname: phpipam
    mem_limit: 1g
    cpus: 0.500    
    ports:
      - "8200:80"
    environment:
      - TZ=America/Sao_Paulo
      - IPAM_DATABASE_HOST=db
      - IPAM_DATABASE_USER=root      
      - IPAM_DATABASE_PASS=p4ssw0rd
      - IPAM_DATABASE_NAME=phpipam
      - IPAM_DATABASE_WEBHOST=%
    restart: unless-stopped
    depends_on:
      - db
    networks:
      interna:
        ipv4_address: 10.20.30.1

  db:
    image: mariadb:latest
    container_name: db-ipam
    mem_limit: 1g
    cpus: 0.500
    environment:
      - MYSQL_ROOT_PASSWORD=p4ssw0rd
    restart: unless-stopped
    volumes:
      - ./phpipam-db-data:/var/lib/mysql
    networks:
      interna:
        ipv4_address: 10.20.30.2

networks:
  interna:
     name: DockerInterna
     ipam:
       config:
            - subnet: 10.20.0.0/16
              gateway: 10.20.254.254
